apiVersion: apps/v1
kind: Deployment
metadata:
  name: cars-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cars-api
  template:
    metadata:
      labels:
        app: cars-api
    spec:
      containers:
        - name: cars-api
          image: cars-api:local
          ports:
            - containerPort: 3001
          env:
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: cars-api-secret
                  key: MONGO_URL
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "256Mi"
